---
title: "*Lurking in the shadows:* The impact of CO~2~ emissions target setting on carbon pricing and environmental efficiency."
author: 
  - Barry Quinn (Queen’s Management School)
  - Ronan Gallagher (University of Edinburgh Business School)
  - Timo Kuosmanen (Aalto Business School)
format: 
  pdf:
    keep-tex: true
editor: visual
bibliography: references.bib
---

# Abstract

This paper studies the impact of CO~2~ emissions target setting. We empirically investigate the targets set during the Kyoto Protocol period using a convex non-parametric least squares system, quantile regressions, and a comprehensive data set of 125 countries. Our findings reveal CO~2~ marginal abatement costs, which: (1) are significantly higher for target setting countries; (2) increase over the sample period; (3) and are an order of magnitude greater than the prevailing emissions pricing mechanisms. The results provide insights into the consequences of policies to curb unwanted by-products in a regulated system and shed light on the price efficiency of carbon markets. Furthermore, we contribute to the debate on emission reduction standard-setting and highlight the importance of shadow price estimates when regulating market instabilities in an emission trading scheme.

\newpage

# Introduction

The World Health Organization predicts significant health risks associated with climate change. Their analysis estimates around 250,000 additional deaths per year from 2030 to 2050, assuming the status quo of current abatement practices and global economic growth[^1]. The reduction of greenhouse emissions and the impact on climate change are existential challenges of the 21st century. Many countries have adopted emissions reductions targets since the dawn of the Kyoto Protocol (hereafter KP)[^2] in response to this challenge. The nature and efficacy in response to this challenge of these targets have attracted considerable conceptual debate (for example, see @De_Angelis2019 ), but few empirical studies on the impact of explicit target setting.

[^1]: These statistics are taken from the WHO factsheet on climate change and health <https://www.who.int/news-room/fact-sheets/detail/climate-change-and-health>

[^2]: The KP was principled on the idea of hard targets for emissions reduction for industrialised nations and the EU. These were developed in tandem with carbon trading mechanisms, the largest of which is the EU Emissions Trading System (EU-ETS). These developments brought not just matters of environmental production efficiency to the fore but also those relating to carbon price discovery.

We attempt to solve this puzzle by testing the differences between target-setting and non-target-setting countries. We use an identification strategy that more accurately estimates the impact of target setting on carbon pricing and environmental efficiency. Specifically, we focus on the KP target setting period and analyse CO~2~ emissions for 125 countries. Considering only CO~2~ emissions allow for a representative sample of non-target setting Countries (non-annexed 1 Countries) and more meaningful group comparisons in our statistical tests. We use quantile system of convex nonparametric least squares regressions (CQR) to estimate shadow prices (see equation (1) in @Kuosmanen.2021 ) and an improved marginal abatement cost (MAC) of CO~2~ emissions [@Xian.2022; @Dai.2020; @Kuosmanen.2020; @Kousmanen.2021]. Convex nonparametric least squares has recently been found to admit a causal interpretation between inefficiency and productivity [@Tsionas.2022]. Moreover, our method allows for an examination of the factors which help explain relative (in)efficiencies.

We find that target setters during the first KP commitment period were more environmentally inefficient than non-target setters, an unintended consequence of the regulation. We also note that countries with a higher degree of industrialisation and those with more urban populations exhibit lower environmental efficiency. Our results also assert that the marginal cost of CO~2~ reduction during the first KP period was an order of magnitude higher than the trading price of CO~2~ in the EU-ETS. This result suggests considerable price inefficiency in the emissions market.

Our findings have important implications for international carbon regulation. Authors have highlighted potential gains in CO~2~ mitigation from emission trading schemes (for example, @Kumar.20207q ). Our findings add to this debate. We show that the shadow prices and market prices of CO~2~ diverge in the KP period, suggestive of a consistent misallocation of the traded allowances in the EU emissions trading scheme (ETS). Our results also show an imbalance in shadow pricing due to target setting. These significant frictions in the price discovery of an ETS market may result in a surplus of allowances, exacerbating market instability, and a lower carbon price. The latter likely weakened the incentives to lower emissions. We argue that when policymakers debate structural measures to promote market stability, such as predefined rules to place unallocated allowances in a market stability reserve, shadow price imbalances due to target setting must be considered\[3\].

In the next section, we review the literature on the impact of the KP on emissions and productive efficiency. Next, we describe the frontier models and data used. We follow with a discussion of our findings and conclusions.

# Literature Review

The academic inquiry into the effective management of climate change has a rich history. Historically, holistic models seek to understand how human development, societal choices, and the natural world integrate and influence each other. At a simplistic level, they can estimate the social cost of carbon pollutants. This top-down approach to the economics of climate change has been at the forefront of the discipline [@Vale2016]. However, such a global approach may prove dated in the face of stalled international coordination on climate change policy.

Against the bedrock of climate science, the KP agreement was an ambitious attempt to coordinate across borders on targets for emissions reduction. The KP set out to differentiate reduction targets equitably in terms of a nation's industrial development, a comparable level of pollution, and the ability to mitigate the ecological damage of global emissions levels. Specifically, countries were categorised into two Annexes. Annex 2 countries, which set explicit targets, were mostly developed nations, with higher industrial production. Annex 1 countries, defined as developing, were not subject to targets, although most ratified the Protocol.

In the run-up to the end of the first commitment period of the KP, there were political moves to create second commitment period targets. The Doha amendment in 2012 extended the scope of the protocol targets to cover the period until 2020. The Doha Amendment was a bridge arrangement up to 2020 until a new global agreement; the Paris Agreement came into force. The Paris agreement has attracted considerable criticism. Commentators cite a lack of explicit targets, ambiguity in regard to sanctions for failing to meet targets, and a more explicit international focus as a critical weakness to country policymakers taking direct ownership of their emissions targets.

As global cooperation has stalled in the last decade, attention in the policy debate has shifted towards bottom-up strategies for climate change mitigation. @Vale2016 argues that the lack of collective political will, in turn, has shifted the nature of the associated academic enquiry. The recent focus on the economics of catastrophic risk insurance, trade and climate, and climate change adaptation represents a shift towards a more realistic investigation of climate policy in an age where the globally coordinated climate action seems illusory.

A common approach to establishing world-wide cost estimates for the reduction of polluting emissions is to establish a global production model. In such a model, based on a set of capital and human inputs, each country acts as a producer of desirable outputs such as GDP at the cost of producing undesirable outputs such as pollutants from industrial activity. Under various assumptions, such a model can reveal each country's relative (in)efficiency,calibrated against a backdrop of global optimal environmental efficiency. Furthermore, abatement of pollution output can be at the marginal cost of the desirable output foregone.

@Zhang1998 document and critique the myriad of marginal abatement cost models. They consider both bottom-up technology-based models and top-down macroeconomic models. They conclude that combining these models best assesses the overall consequences of controlling CO2 emissions. @Nordhaus1999 use a scenario-based approach to analyse the economics of various trading emission schemes (ETS) for Annex I countries for the KP. They find costs of the ETS's are seven times greater than the benefits, two/thirds of the net global cost of \$716 billion, are borne by the US\[\^4\] and conclude that the proposed schemes are highly cost-ineffective.

\[\^4\]: Compared to a \*so-called" efficient abatement strategy for global temperature reduction, the proposed strategy was eight times more costly.

This early work was suggestive of a broad approach to abatement cost analysis beyond the consideration of CO^2^ associated pollution. @Reilly1999 use the Regional Integrated Model of Climate and Economy (RICE) to show that a multi-gas control strategy could significantly reduce the costs of fulfilling the KP compared with a CO^2^-only strategy. They argue that the global warming mitigation potential of the KP is limited and argue for a more comprehensive multi-gas approach. @Burniaux2000 extend previous OECD analysis to emission abatement of methane and nitrous oxide. They conclude that the economic costs of implementing the targets in the KP are lower than suggested by previous CO^2^-only results. In the longer term, most abatement will likely have to come from CO^2^, and the inclusion of other gases in the analysis may not substantially alter estimates of economic costs.

In the later years of the KP period, researchers considered a more statistically sophisticated approach for analysing the KP. @Buonanno2003 adapt the RICE integrated assessment model to account for endogenous technical change\[\^5\] and shows that results are significantly impacted when modelling R&D. They find that total costs of compliance with Kyoto; are higher with induced technical change; are reduced when trading permits are introduced, and technological spillover reduces the incentive for R&D, but overall costs are higher in the presence of spillovers. @McKibbin2004 update their earlier estimates of the cost of the KP using the G-Cubed model, taking into account the new sink allowances from recent negotiations as well as allowing for multiple gases and new land clearing estimates. They perform a sensitivity analysis of compliance costs to unexpected changes in future economic conditions. The paper evaluates the policies under two plausible alternative assumptions about a single aspect of the future world economy: the rate of productivity growth in Russia. They find moderate growth in Russia would raise the cost of the KP by as much as fifty per cent but would have little effect on the cost of the alternative policy. They conclude that the KP is inherently unstable because unexpected future events could raise compliance costs substantially and place enormous pressure on governments to rescind the agreement. The alternative policy would be far more stable because it does not subject future governments to adverse shocks in compliance costs. @Fischer2006 find that estimates of marginal abatement costs for reducing carbon emissions in the United States by the significant economic-energy models vary by a factor of five, undermining support for mandatory policies to reduce greenhouse gas emissions. Their meta-analysis explains which modelling assumptions are most important for understanding these cost differences and argues for developing more consistent modelling practices for policy analysis.

\[\^5\]: They explore three formulations; technical change is endogenous and enters the production function via the domestic stock of knowledge; there is an additional effect of domestic stock of knowledge on the emission-output ratio; the output of domestic R&D spills over the other regions' productivity and emission-output ratio.

In more recent studies researchers focus on how a country's economic characteristics fluctuate with abatement challenges. @Halkos2014 apply a probabilistic DEA approach to estimate conditional and unconditional environmental efficiency of 110 countries in 2007. They find that a country's environmental efficiency is influenced in a non-linear mannerby both the obliged percentage levels of emission reductions and the duration forwhich a country has signed the KP. @Cifci2018 use regression techniques to illustrate the conflicting political strands of the climate change argument. The results show that the KP reduced Annex I countries' GHG emissions by approximately 1 million metric tons of CO2 equivalent relative to non-Annex I countries. Contrariwise, these countries experienced an average reduction in GDP per capita growth of 1-2 per cent relative to non-Annex I countries. Both findings illustrate that the international climate change agreements are fragile due to the clash of short-term political goals with long-term reduction ambitions.

# Empirical Design

We model the global economy as a production machine. Capital and labour are inputs, creating economic output (desirable). However in doing so the economic "machine" also produces CO2 emissions which are undesirable. We use the concept of an efficiency frontier to model combinations of inputs and outputs. We do so not in a deterministic way, but using stochastic non-parametric methods. This affords us the advantage of not having to specify a functional form of the input-output relationship a priori and also the ability to model noise in the data. We are concerned both with measuring environmental inefficiency (distance from the frontier), but perhaps more subtly shadow costs. These shadow costs can be interpreted as opportunity costs which allow us to price CO2 emissions, or put differently to calculate the marginal cost of CO2 abatement.

The primary focus of our analysis is shadow prices estimation for CO^2^ emissions from fossil fuels. Previous studies have provided inaccurate measures as a result of several methodological shortcomings including:

\* only considering downscaling of production and not increases in input use.

\* measuring estimates on the frontier, ignoring the actual level of performance.

\* deterministic estimation, which explicitly ignores the impact of noise in the data.

These factors lead to overestimation of both shadow prices and group differences in shadow prices between target setting and non-target setting countries. Our study uses convex quantile regression methods to estimate local approximations of shadow prices calibrated using observed inefficiencies. Specifically, we exploit the CQR framework in @Kuosmanen.2021 to estimate shadow prices at observed performance levels. Importantly, this approach is robust to the observed heterogeneity, the choice of direction vector and accommodates noise-based uncertainty. The following linear programming problem is solved to estimate the distance function:

$$
\begin{equation}\begin{split}& \underset{\alpha,\beta,\gamma,\delta,\epsilon^-,\epsilon^+}{\text{min}} (1-\tau) \sum^{T}_{t=1} \sum^{n}_{i=1}\epsilon^-_{it} + \tau \sum^{T}_{t=1}  \sum^{n}_{i=1}\epsilon^+_{it}  \\&\text{s.t.} \\&\gamma^{'}_{it}y_{it}=\alpha_{it}+\beta^{'}_{it}x_{it}+\delta^{'}_{it}b_{it} + \omega Z_{it} -\epsilon^-_{it}+\epsilon^+_{it} \; \forall i ,\forall t \\&\alpha_{it}+\beta^{'}_{it}x_{it}+\delta^{'}_{it}b_{it}-\gamma^{'}_{it}y_{it} \leq \alpha_{hs}+\beta^{'}_{hs}x_{it}+\delta^{'}_{hs}b_{it}-\gamma^{'}_{hs}y_{it} \; \forall i,h ; \forall t,s \\& \beta^{'}_{it}g^x+\delta^{'}_{it}g^b+\gamma^{'}_{it}g^y=1 \; \forall i,t\\& \beta_{it} \geq0,\gamma_{it} \geq0,\delta_{it} \geq0 \; \forall i,t \\& \epsilon^-_{it} \geq0, \epsilon^+_{it} \geq 0 \; \forall i,t\end{split}\end{equation}
$$ {#eq-1}

@eq-1 [\^6] is a probabilistic distance function, where the two errors terms ($\epsilon^-$ and $\epsilon^+$) allow for deviations from the frontier, and $\tau$ defines the quantile. We estimate the model using a balanced panel of 105 countries for five years (2008-2012) where the $Z$ vector includes, trade to GDP ratio, the percentage of the population which is urban, a dummy to the indicator if the country is a target setting, and a set of year dummies. These environmental variables adjust for observed cross-country and through time fluctuation in the production technology. The estimated model results in performance adjusted dual prices $\gamma^{'}_{it},\beta^{'}_{it} ,\delta^{'}_{it}$ which serve as inputs for the marginal abatement calculations. An appealing feature of the specification in equation 1 is a separately estimated intercept for each observation; $\alpha_{it}$. These intercept terms are analogous to random effects in hierarchical model statistics, capturing unobserved time series and cross-sectional variation.

\[\^6\]: We use GAMS software to encode our CQR and the CPLEX solver to find an optimal solution.

## Marginal abatement

Marginal abatement estimation uses a series of levels to find the local quantile $\tau^{*}$ for each observed data point. For example, a set of ten quantile levels $\tau=(0.05,0.15,0.25,0.35,0.45,0.55,0.65,0.75,0.85,0.95)$ \[\^7\]. In general, the number of quantiles is not fixed but should depend on sample size and signal to noise ratio. @Kuosmanen.2020 note that in the traditional approach to shadow pricing using frontier estimation, marginal abatement costs and shadow prices are interchangeable terms. This is because prior approaches only use bad output shadow prices measured in forgone good output units. They expand the marginal abatement cost definition to include incremental use of inputs by considering an optimal combination of shadow price definitions:

1.  The marginal rate of transformation between good and bad outputs (MRT).
2.  The marginal product of inputs on outputs (MP).

In our study, we similarly calculate marginal abatement costs as:

1.  Find the largest expectile ($\tau^{*}$) for which the residual ($\epsilon^+ + \epsilon^-$) is non-negative.
    i.  For most observations, we find the nearest expectile by checking where the residual changes sign. For those observations, we take the weighted average of the shadow prices of the nearest executives, weighted by . For some observations, residuals are positive (or negative) for all executives (the best and the worst performers, respectively). For those, we use shadow prices of the highest/lowest expectile.
2.  Calculate MRT and MP as the weighted average of quantiles for ($\tau^{*}$) and ($\tau^{*+1}$) weighted by the distance to the frontier of the quantiles(i.e. the absolute value of the residuals). Specifically, these can be thought of as the sub derivatives with respect to the bad outputs from the distance function, where the marginal rate of substitution of output \$i\$ on bad output $j$ is $MRT_{\tau}(y_{i},b_{j})=-\frac{\delta \vec{D}_{\tau}/\delta b_{j}}{\delta \vec{D}_{\tau}/\delta y_{i}}$. Similarly the MP of input k on bad output j is $MP_{\tau}(x_{k},b_{j})=\frac{\delta \vec{D}_{\tau}/\delta b_{j}}{\delta \vec{D}_{\tau}/\delta x_{k}}$
3.  Use the results from step 2, the marginal abatement cost (MAC) for bad output is defined as:
4.  $$
    \begin{equation}MAC(b_{j})=\displaystyle \min_{i,k}\{p_{i}MRT_{\tau}(y_{i},b_{j}), w_{k}MP_{\tau}(x_{k},b_{j})\}\end{equation}
    $$ {#eq-2}
    i.  In @eq-2 $p_{i}$ is the price of output $i$ and $w_{k}$ is the price of input $k$. This flexible definition of the MAC provides multiple opportunities for abatement. Specifically, bad output $j$ can be abated by either reducing *good* outputs (i.e., downscaling the GDP activity) or increasing the input use (for example, investment in the labour force or capital stock). This approach uses the least-cost alternative. In the case where the good outputs possess a monetary value, the sub derivatives (dual prices) provide monetary shadow prices for bad outputs, and the above equation simplifies to:

$$
\begin{equation}MAC(b_{j})=\displaystyle \min_{i,k}\{MRT_{\tau}(y_{i},b_{j}), MP_{\tau}(x_{k},b_{j})\} \end{equation}
$$ {#eq-3}

In the above calculation, it is essential to ensure that the MRT and MP enter the model simultaneously, given the scale of the inputs and outputs entering the model. In our model, as both capital stock and GDP enter the model in billions of dollars, the MRT and MP are directly comparable in terms of minimum cost.

## Application of Statistical Test

In order to examine the impact of KP on environmental efficiency and shadow prices (MACs) for CO~2~ we want to look at group differences between those countries who signed up to explicit emissions reduction targets and those who did not. We utilize a test for group differences in shadow prices first proposed by @Gallagher.2019.

Appendix A:1 details the theoretical exposition of shadow price group difference testing .Suppose we have two series of the output ratio y2/y1, representing two groups of firms observed in the same period or the same sample of firms observed in two different periods. There are several methods for testing whether the two series are significantly different.

An obvious possibility is to apply a two-sample t-test for testing the equality of means or the F-test for equal variances. This test requires either that sample size is sufficiently large for asymptotic inferences or that the ratio y2/y1 is normally distributed.

There are also several nonparametric alternatives. The (Wilcoxon) Mann-Whitney U tests whether the medians of two independent distributions are different. Another possibility is the two-sample Kolmogorov-Smirnov test. If there is a pair of series(e.g., the same firms observed in two different periods), then nonparametric rank-order tests such as Spearman's rho and Kendall's tau can be used to test for correlation between two series of y2/y1.

### Testing procedure

There are three steps to the testing procedure for the difference in the ratio series y2/y1. The first two steps are preliminary in that they establish the statistical properties of the series, which informs the choice of group difference test in the three-step.

1.  Test the empirical distribution of the series for normality. Whether the series is normally distributed determines whether a parametric or nonparametric test is needed. @Stephens1986 recommend the use of a normality test introduced by @Anderson1952 @Anderson1954. This procedure is a rank-sum test for goodness of fit based on the empirical distribution and has the advantage of giving more weight to the tails of the distribution.

2.  Test the homogeneity of variance in the two groups. If step 1 establishes normality, a simple F test of the homogeneity of variance can be performed. In the presence of non-normality, we turn to the @Brown1974 test, which extended the @Levene1961 ANOVA procedure applied to absolute deviations from the corresponding group mean. This Brown-Forsythe test transforms the variances into the absolute values of their deviations from the median. It uses a ratio of this transformed data as test statistics (See @OBrien1981 for full explanation).

3.  If the equal group variance and the normality assumptions are not rejected, then perform a Welch t-test for group mean differences [@Welch1947]. The Kolmogorov-Smirnov nonparametric test provides a more robust statistical inference [@Conover1999]. If only the normality assumption is rejected, the Wilcoxon Mann Whitney test is more appropriate.

# Data and variables

The KP offers a unique empirical framework to assess the effects of explicit target setting in climate change policy. The first commitment period for the KP was 2008 to 2012. Countries defined as developing (non-annexe 1) were not subject to targets, although most ratified the Protocol. The US was the only signatory of the Protocol that did not ratify. This decision was likely the combination of a weak green lobby in Washington DC [@Hovi2012], perceived excessive compliance costs [@Manne2004] , poor public understanding of climate change [@Brechin2003], and a strong energy lobby during President G.W. Bush's tenure.[\^7]. In the run-up to the end of the first commitment period, there were political moves to create targets for a second commitment period culminating in the Paris Agreement. However critics argued that the Paris agreement fell well short of the explicit target setting that was central to the KP. For these reasons, we focus on emissions data from 2008 to 2012, the first commitment period. For this period, it is easier to say definitively who had set targets and who had not. The lines were blurred post-2012 when a new negotiation phase began. The Protocol set a target for emissions of a basket of greenhouse gases[\^8] to be reached by the signatories in the period 2008-2012. This paper extends the work of @Halkos2014. To the best of our knowledge, it is the first study to explicitly provide an economic cost of these emissions targets[\^9].

\[\^7\] : Andorra, Palestine, South Sudan and the Vatican also do not follow the Protocol. Canada ratified but withdrew effective in December 2012.

\[\^8\]: Carbon dioxide, CO~2~; methane, CH~4~; nitrous oxide, NO~2~; sulphur fluoride, SF~6~; hydrofluorocarbons, HFCs; and perfluorocarbons; PFCs.

\[\^9\]: @Halkos2014 investigate the overall environmental efficiency impact of the KP.

We specify a two input-two output frontier efficiency model. Specifically, we define GDP as a desirable output, CO~2~ emissions from fuel combustion as an undesirable output, and labour force numbers and capital stock as inputs. GDP and labour force numbers are sourced from the World Bank. The capital stock captures both current and past accumulations of capital investment. Finally, to capture cross-country and time-varying heterogeneity in CO~2~ production, we use several environmental variables. Table 1 provides a detailed description of the modelling variables.

```{r table 1 descriptions, results="asis"}
library(WDI)

library(RJSONIO)

VarCodes<-c("NY.GDP.MKTP.PP.KD",

            "SL.TLF.TOTL.IN",

            "NE.TRD.GNFS.ZS",

            'SP.URB.TOTL.IN.ZS')

GDP<-WDIsearch(VarCodes[1],field="indicator",short = F)

Lab<-WDIsearch(VarCodes[2],field="indicator",short = F)

Trade<-WDIsearch(VarCodes[3],field="indicator",short = F)

Pop<-WDIsearch(VarCodes[4],field="indicator",short = F)

info<-as.data.frame(rbind(GDP,Lab,Trade,Pop),row.names = F,stringsAsFactors = F) %>% filter(description!="")

text_tbl<-tibble(Type=c("Undesirable Output","Desirable Output",rep("Input",2),rep("Enviromental Variable",4)),Variable=c("CO2 emissions from fossil fuel (Millions of metric tonnes)",info$name[1:2],"Capital Stock, PPP (constant international $Billions)",info$name[3:4],"Target Setting Indicator","Year Indicators"),Detail=c("

Emissions were calculated using IEA energy databases and the default methods and emission factors given in the 2006 GLs for National Greenhouse Gas Inventories.",info$description[1:2],"Total capital stock is the sum of government capital stock, private capital stock, and public-private partnerships (PPP) capital stock.  When the PPP capital stock is missing we assume zero.",info$description[3:4],"This variable takes a value of 1 for a country which committed to a hard target of emission reduction during the Kyoto Protocol period and zero otherwise.","A proxy for unobserved between group temporal variation"),Source=c("International Energy Agency" ,info$sourceOrganization[1:2],"IMF and World Bank",info$sourceOrganization[3:4],rep("author's own calculation",2)))

text_tbl %>% flextable()
```

We use the International Energy Association (IEA) database\[\^10\] which provides the most extensive global coverage of CO2 emission data. This database estimates CO2 from fuel emission measured in Metric Tonnes for over 140 countries from 1960 to 2016. After removing countries with missing observations, we have a balanced sample of 525 observations for 2008-2012. Table 2 describes the countries in the sample in terms of target-setting.

\[\^10\]: <http://data.iea.org/payment/products/115-co2-emissions-from-fuel-combustion-2018-edition-coming-soon.aspx>

# References
